### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by devfemibadmus** [AbdulConsole/mfcLab#7]
```MD
# MFCcySecLab

A simple MFCcySecLab attendance sheet. This markdown page is a test site, not official. So all Documentations here are not official.

This is a beautiful site in the making - [Abdul Console](https://github.com/AbdulConsole)

This is my assignment - Firdausi Isa

This is a great web development starting point by - [Ismail Isah](https://github.com/ismailisah)

This is a web developer - Sumayyah Bamba

## Names
- [Abdul Console](https://github.com/AbdulConsole)
- [Firdausi Isa](https://github.com/firdausiisa)
- [Ismail Isah](https://github.com/ismailisah)
- [Sumayyah Bamba](https://github.com/Sumeeey)

```

# MFCcySecLab

A simple MFCcySecLab attendance sheet. This markdown page is a test site, not official. So all Documentations here are not official.

This is a beautiful site in the making - [Abdul Console](https://github.com/AbdulConsole)

This is my assignment - Firdausi Isa

This is a great web development starting point by - [Ismail Isah](https://github.com/ismailisah)

This is a web developer - Sumayyah Bamba

## Names
- [Abdul Console](https://github.com/AbdulConsole)
- [Firdausi Isa](https://github.com/firdausiisa)
- [Ismail Isah](https://github.com/ismailisah)
- [Sumayyah Bamba](https://github.com/Sumeeey)

no mind me ooooo

**Comment by AbdulConsole** [comment]
Thanks brother, you are super motivating.
